version: '3.8'

services:
  db-atividade:
    image: postgres:14
    hostname: db
    restart: unless-stopped
    ports:
      - '${SERVICE_ATIVIDADE_DATABASE_PORT:?SERVICE_ATIVIDADE_DATABASE_PORT env var is missing on .env file}:5432'
    environment:
      POSTGRES_DB: ${SERVICE_ATIVIDADE_DATABASE_NAME:?SERVICE_ATIVIDADE_DATABASE_NAME env var is missing on .env file}
      POSTGRES_USER: ${SERVICE_ATIVIDADE_DATABASE_USERNAME:?SERVICE_ATIVIDADE_DATABASE_USERNAME env var is missing on .env file}
      POSTGRES_PASSWORD: ${SERVICE_ATIVIDADE_DATABASE_PASSWORD:?SERVICE_ATIVIDADE_DATABASE_PASSWORD env var is missing on .env file}
    volumes:
      - ./servico-atividade/data/db:/var/lib/postgresql/data

  api-atividade:
    build:
      context: .
      dockerfile: ./Dockerfile
    hostname: api
    restart: unless-stopped
    ports:
      - '${SERVICE_ATIVIDADE_API_PORT:?SERVICE_ATIVIDADE_API_PORT env var is missing on .env file}:${SERVICE_ATIVIDADE_API_PORT}'
    env_file:
      - .env
    environment:
      NODE_ENV: 'development'
      DATABASE_HOST: 'db'
      DATABASE_PORT: '5432'
      DATABASE_URL: 'postgresql://${SERVICE_ATIVIDADE_DATABASE_USERNAME}:${SERVICE_ATIVIDADE_DATABASE_PASSWORD}@db:5432/${SERVICE_ATIVIDADE_DATABASE_NAME}?schema=public'
    volumes:
      - ./servico-atividade:/home/node/servico-atividade
    depends_on:
      - db-atividade
